# Generated by Django 3.0.4 on 2020-06-21 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True, unique=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, db_column='Data_de_nascimento', null=True)),
                ('numero_telemovel', models.IntegerField(blank=True, db_column='Numero_telemovel', null=True)),
                ('cartão_cidadão', models.IntegerField(blank=True, db_column='Cartão_cidadão', null=True)),
                ('deficiencias', models.CharField(blank=True, db_column='Deficiencias', max_length=255, null=True)),
                ('permitir_localização', models.IntegerField(blank=True, db_column='Permitir_localização', null=True)),
                ('utilizar_dados_pessoais', models.IntegerField(blank=True, db_column='Utilizar_dados_pessoais', null=True)),
                ('tema_do_website', models.IntegerField(blank=True, db_column='Tema_do_website', null=True)),
                ('user_type', models.IntegerField(db_column='User_type')),
                ('daltonico', models.IntegerField(blank=True, db_column='Daltonico', null=True)),
                ('validado', models.IntegerField(db_column='Validado')),
                ('check_in_state', models.IntegerField(blank=True, db_column='Check_in_state', null=True)),
                ('password', models.CharField(db_column='Password', max_length=500)),
                ('departamentoid', models.ForeignKey(blank=True, db_column='DepartamentoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atividades.Departamento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('unidade_orgânicaid', models.ForeignKey(blank=True, db_column='Unidade OrgânicaID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atividades.UnidadeOrganica')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilizador',
            },
        ),
    ]
