# Generated by Django 3.0.4 on 2020-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_de_chegada', models.DateField(blank=True, db_column='Hora_de_chegada', null=True)),
                ('hora_de_partida', models.DateField(blank=True, db_column='Hora_de_partida', null=True)),
                ('tipo_de_transporte', models.CharField(blank=True, db_column='Tipo_de_transporte', max_length=255, null=True)),
                ('capacidade', models.IntegerField(blank=True, db_column='Capacidade', null=True)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
    ]
