# Generated by Django 3.0.4 on 2020-03-28 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaAbertoConf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, db_column='Dia', null=True)),
                ('preco_economico_aluno', models.FloatField(blank=True, db_column='Preco_economico_aluno', null=True)),
                ('preco_normal_aluno', models.FloatField(blank=True, db_column='Preco_normal_aluno', null=True)),
                ('preco_economico_outro', models.FloatField(blank=True, db_column='Preco_economico_outro', null=True)),
                ('preco_outro', models.FloatField(blank=True, db_column='Preco_outro', null=True)),
            ],
            options={
                'db_table': 'ementa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_de_partida', models.TimeField(blank=True, db_column='Hora_de_partida', null=True)),
                ('Hora_de_chegada', models.TimeField(blank=True, db_column='Hora_de_chegada', null=True)),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={},
        ),
        migrations.CreateModel(
            name='TransporteUniversitarioHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(blank=True, db_column='Origem', max_length=255, null=True)),
                ('destino', models.CharField(blank=True, db_column='Destino', max_length=255, null=True)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('horarioid', models.ForeignKey(db_column='HorarioID', on_delete=django.db.models.deletion.CASCADE, to='diaAbertoConf.HorarioTransporte')),
                ('transporteid', models.ForeignKey(db_column='TransporteID', on_delete=django.db.models.deletion.CASCADE, to='diaAbertoConf.Transporte')),
            ],
            options={
                'db_table': 'transporte_universitario_horario',
            },
        ),
    ]
