# Generated by Django 3.0.4 on 2020-03-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaAbertoConf', '0002_auto_20200328_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporte',
            old_name='tipo_de_transporte',
            new_name='tipo_transporte',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='hora_de_chegada',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='hora_de_partida',
        ),
    ]
