# Generated by Django 3.0.4 on 2020-03-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaAbertoConf', '0003_auto_20200328_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariotransporte',
            old_name='Hora_de_chegada',
            new_name='hora_de_chegada',
        ),
    ]
