# Generated by Django 3.0.4 on 2020-04-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaAbertoConf', '0004_auto_20200331_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariotransporte',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transporteuniversitariohorario',
            options={'managed': False},
        ),
    ]
