# Generated by Django 3.0.4 on 2020-04-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaAbertoConf', '0005_auto_20200401_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariotransporte',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transporteuniversitariohorario',
            options={'managed': True},
        ),
    ]
