# Generated by Django 3.0.4 on 2020-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaAbertoConf', '0007_auto_20200401_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariotransporte',
            name='data',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='hora_chegada',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='hora_partida',
        ),
        migrations.AddField(
            model_name='horariotransporte',
            name='hora_de_chegada',
            field=models.TimeField(blank=True, db_column='Hora_de_chegada', null=True),
        ),
    ]
