# Generated by Django 3.0.4 on 2020-04-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaAbertoConf', '0008_auto_20200401_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariotransporte',
            name='hora_de_chegada',
        ),
    ]
