# Generated by Django 3.0.4 on 2020-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_auto_20200327_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('duracao', models.IntegerField(blank=True, db_column='Duracao', null=True)),
                ('limite_de_participantes', models.IntegerField(blank=True, db_column='Limite_de_participantes', null=True)),
                ('validada', models.IntegerField(blank=True, db_column='Validada', null=True)),
                ('tipo_atividade', models.CharField(blank=True, db_column='Tipo_atividade', max_length=255, null=True)),
                ('public_alvo', models.CharField(blank=True, db_column='Public_alvo', max_length=255, null=True)),
            ],
            options={
                'db_table': 'atividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andar', models.IntegerField(blank=True, db_column='Andar', null=True)),
                ('sala', models.IntegerField(blank=True, db_column='Sala', null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('indoor', models.IntegerField(blank=True, db_column='Indoor', null=True)),
            ],
            options={
                'db_table': 'local',
                'managed': False,
            },
        ),
    ]
