# Generated by Django 3.0.4 on 2020-03-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_atividade_departamento_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicifio',
            name='nome_edificio',
            field=models.CharField(blank=True, db_column='Nome_edificio', max_length=255, null=True),
        ),
    ]
