# Generated by Django 3.0.4 on 2020-03-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_edicifio_nome_edificio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edicifio',
            new_name='Edificio',
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'managed': True},
        ),
    ]
