# Generated by Django 3.0.4 on 2020-03-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_auto_20200328_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='public_alvo',
            new_name='publico_alvo',
        ),
        migrations.AddField(
            model_name='atividade',
            name='localid',
            field=models.ForeignKey(db_column='LocalID', default='', on_delete=django.db.models.deletion.CASCADE, to='atividades.Local'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='validada',
            field=models.BooleanField(blank=True, db_column='Validada', null=True),
        ),
    ]
