# Generated by Django 3.0.4 on 2020-03-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0007_auto_20200328_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={},
        ),
    ]
