# Generated by Django 3.0.4 on 2020-03-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0008_auto_20200328_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='publico_alvo',
            new_name='public_alvo',
        ),
        migrations.AddField(
            model_name='atividade',
            name='editavel',
            field=models.BooleanField(blank=True, db_column='Editavel', null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidadeorganicaid',
            field=models.ForeignKey(db_column='UnidadeOrganicaID', default='', on_delete=django.db.models.deletion.CASCADE, to='atividades.UnidadeOrganica'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='utilizadorid',
            field=models.ForeignKey(db_column='UtilizadorID', default='', on_delete=django.db.models.deletion.CASCADE, to='atividades.Utilizador'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='localid',
            field=models.ForeignKey(db_column='LocalID', on_delete=django.db.models.deletion.CASCADE, to='atividades.Local'),
        ),
    ]
