# Generated by Django 3.0.4 on 2020-03-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0009_auto_20200328_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='unidadeorganicaid',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='utilizadorid',
        ),
    ]
