# Generated by Django 3.0.4 on 2020-03-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0010_auto_20200328_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='unidadeorganicaid',
            field=models.ForeignKey(db_column='UnidadeOrganicaID', default='', on_delete=django.db.models.deletion.CASCADE, to='atividades.UnidadeOrganica'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='utilizadorid',
            field=models.ForeignKey(db_column='UtilizadorID', default='', on_delete=django.db.models.deletion.CASCADE, to='atividades.Utilizador'),
        ),
    ]
