# Generated by Django 3.0.4 on 2020-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0013_atividadedepartamento_atividadematerial_atividadetematica_material_tematica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_de_inicio', models.TimeField(blank=True, db_column='Hora_de_inicio', null=True)),
            ],
            options={
                'db_table': 'sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
            ],
            options={
                'db_table': 'sessao_atividade',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'managed': True},
        ),
    ]
