# Generated by Django 3.0.4 on 2020-03-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0014_auto_20200329_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='indoor',
            field=models.BooleanField(blank=True, db_column='Indoor', null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='sala',
            field=models.CharField(blank=True, db_column='Sala', max_length=255, null=True),
        ),
    ]
